plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs8.github.io # the base hostname & protocol for your site
baseurl: /w19-matni  # the subpath of your site, e.g. "/blog"


include:
  - _pages
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - .bundle

course: "CS8"
qtr: "W19"
qxx: "w19"
instructor: "Matni"
quarter: "Winter 2019"
github_org_name: ucsb-cs8-w19-matni
github_org_url: https://github.com/ucsb-cs8-w19-matni

ta_list: "Muqsit, Zexi, Keqian, and Alex"
ta_list_full: "M. Muqsit Nawaz, Zexi Huang, Keqian Li, Alex Ermakov" 
mentors_list: ""
discussion_section_times: ""

github_url: https://github.com/ucsb-cs8/w19-matni
mentor_url: 


start_week: 0
start_date: 2019-01-06 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true
sections:

cal_dates: >
  [
    {"label":"W19 1st day of instruction", "date":"2019-01-07" },	
    {"label":"Univ Holiday", "date":"2019-01-21" },
    {"label":"Univ Holiday", "date":"2019-02-18" },
    {"label":"W19 instruction ends", "date":"2019-03-15" },
    {"label":"W19 finals start", "date":"2019-03-18" },
    {"label":"W19 finals end", "date":"2019-03-22" },
    {"label":"W19 qtr ends", "date":"2019-03-22" }
  ]

hwk_drop_lowest: one


kramdown:
   parse_block_html: true

exclude:

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
